# -*- coding: utf-8 -*-
"""bubble sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEUE8u0ExWdKutv_rgil4pHovleX3IUN
"""

size = int(input("Enter the size of Array: "))
arr = []

for i in range(0,size):
  x = int(input())
  arr.append(x)

for j in range(0,size):
  size -= 1
  for i in range(0,size):
    if arr[i] > arr[i+1]:
      arr[i], arr[i+1] = arr[i+1], arr[i]

print(arr)