# -*- coding: utf-8 -*-
"""insertion sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U3b4ibRGQo2FDrw-ZSZjf2KkAAqcOvbY
"""

size = int(input("Enter the size of Array: "))
arr = []

for i in range(0,size):
  x = int(input())
  arr.append(x)

for i in range(1,size):
  num = arr[i]
  index = i
  while index > 0 and num < arr[index-1]:
    arr[index] = arr[index-1]
    index -= 1
  arr[index] = num

print(arr)