# -*- coding: utf-8 -*-
"""merge sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RQmHPtqZqHugRx9F2VaA9JQsqqYn5OWB
"""

# MergeSort in Python


def mergeSort(array):
    if len(array) > 1:

        #  mid is the point where the array is divided into two subarrays
        mid = len(array)//2
        arr1 = array[:mid]
        arr2 = array[mid:]

        # Sort the two halves
        mergeSort(arr1)
        mergeSort(arr2)

        i = j = k = 0
        while i < len(arr1) and j < len(arr2):
            if arr1[i] < arr2[j]:
                array[k] = arr1[i]
                i += 1
            else:
                array[k] = arr2[j]
                j += 1
            k += 1

        while i < len(arr1):
            array[k] = arr1[i]
            i += 1
            k += 1

        while j < len(arr2):
            array[k] = arr2[j]
            j += 1
            k += 1


# Print the array
def printList(array):
    for i in range(len(array)):
        print(array[i], end=" ")
    print()

array = []
size = int(input("Enter the size of the Array: "))
for i in range(0,size):
  x = int(input())
  array.append(x)
mergeSort(array)
print("Sorted array is: ")
printList(array)

