# -*- coding: utf-8 -*-
"""quick sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J0ggq5INSNOmX7cd1nhmbGaBR3ra5jiC
"""

def partition(arr, low, high):
    i = (low-1) 
    pivot = arr[high] 
  
    for j in range(low, high):
        if arr[j] <= pivot:
  
            i = i+1
            arr[i], arr[j] = arr[j], arr[i]
  
    arr[i+1], arr[high] = arr[high], arr[i+1]
    return (i+1)

  
def quickSort(arr, low, high):
    if len(arr) == 1:
        return arr
    if low < high:
  

        pi = partition(arr, low, high)

        quickSort(arr, low, pi-1)
        quickSort(arr, pi+1, high)

arr = []
n = int(input("Enter the size of array: "))

for i in range(0,size):
  x = int(input())
  arr.append(x)
quickSort(arr, 0, n-1)
print("Sorted array is:"+str(arr))