# -*- coding: utf-8 -*-
"""selection sort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GUa_GTuenVNRUwEsEB5dr6M8D5ZSv2UD
"""

size = int(input("Enter the size of Array: "))
arr = []

for k in range(0,size):
  element = int(input())
  arr.append(element)

for i in range(len(arr)):
    idx = i
    for j in range(i+1, len(arr)):
        if arr[idx] > arr[j]:
            idx = j 
    arr[i], arr[idx] = arr[idx], arr[i]

print(arr)